blogPosts/urls.py
# blogPosts/urls.py
from django.urls import path
from blogPosts import views

app_name = 'blogPosts'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.show, name='show'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

seminar/urls.py
# seminar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import blogPosts.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blogPosts.views.index, name='index'),
    path('posts/', include('blogPosts.urls')),
]

blogPosts/models.py
# blogPosts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)

    def update_date(self):
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blogPosts/views.py
# blogPosts/views.py
from django.shortcuts import render, redirect
from .models import Post


def index(request):
    if request.method == 'GET':  # index
        posts = Post.objects.all()
        return render(request, 'blogPosts/index.html', {'posts': posts})
    elif request.method == 'POST': # create
        title = request.POST['title']
        content = request.POST['content']
        Post.objects.create(title=title, content=content)
        return redirect('blogPosts:index')


def new(request):
    return render(request, 'blogPosts/new.html')


def show(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'blogPosts/show.html', {'post': post})


def edit(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'blogPosts/edit.html', {'post': post})


def update(request, id):
    title = request.POST.get('title')
    content = request.POST.get('content')
    Post.objects.filter(id=id).update(title=title, content=content)
    return redirect('blogPosts:index')


def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('blogPosts:index')

blogPosts/templates/base.html
{% comment %} blogPosts/templates/base.html {% endcomment %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>SNUGDC</title>
        {% load static %}
        {% load sass_tags %}
        <link rel="stylesheet" type="text/css" href="{% sass_src 'blogPosts/scss/style.scss' %}">
    </head>
    <header>SNUGDC Blog</header>
    <body>
    {% block content %}
    {% endblock %}
    </body>
</html>

blogPosts/templates/blogPosts/edit.html
{% extends 'base.html' %}
{% comment %} /blogPosts/templates/blogPosts/index.html {% endcomment %}

{% block content %}
    <h1>Edit Post</h1>
    <form action="/posts/{{ post.id }}/update/" method="POST">
        {% csrf_token %}
        <h3>title</h3>
        <input type="text" name="title" value="{{ post.title }}" />
        <p>content</p>
        <textarea type="text" name="content" rows="30" cols="50">{{ post.content }}</textarea> <br />
        <input type="submit" value="submit" />
    </form>
{% endblock content %}

blogPosts/templates/blogPosts/index.html
{% extends 'base.html' %}
{% comment %} /blogPosts/templates/blogPosts/index.html {% endcomment %}

{% block content %}
    <h1>POSTS</h1>
    <a href="{% url 'blogPosts:new' %}">new post</a>
    {% for post in posts %}
        <div style="border: 1px solid grey;">
            <a href="{% url 'blogPosts:show' id=post.id %}">
                <h3>{{ post.title }}</h3>
            </a>
            <a href="{% url 'blogPosts:edit' id=post.id %}">edit</a>
            <a href="{% url 'blogPosts:delete' id=post.id %}">delete</a>
        </div>
    {% endfor %}
    <form action="{% url 'blogPosts:index' %}" method="POST">
        {% csrf_token %}
        <p>title
        <input name="title" /> </p>
        <p>content</p>
        <textarea name="content" rows="5" cols="50"></textarea> <br />
        <input type="submit" value="submit" />
    </form>
{% endblock content %}

blogPosts/templates/blogPosts/new.html
{% extends 'base.html' %}
{% comment %} ./blogPosts/templates/blogPosts/new.html {% endcomment %}

{% block content %}
    <h1>new post</h1>
    <form action="{% url 'blogPosts:index' %}" method="POST">
        {% csrf_token %}
        <p>title</p>
        <input name="title" /> <br />
        <p>content</p>
        <textarea name="content" rows="30" cols="50"></textarea> <br />
        <input type="submit" value="submit" />
    </form>
{% endblock content %}

blogPosts/templates/blogPosts/show.html
{% extends 'base.html' %}
{% comment %} /blogPosts/templates/blogPosts/show.html {% endcomment %}

{% block content %}
        <div>
            <a href="{% url 'blogPosts:index' %}">home</a>
            <h1>{{ post.title }}</h1>
            <p style="width: 70%;">{{ post.content }}</p>
            <a href="{% url 'blogPosts:edit' id=post.id %}">edit</a>
            <a href="{% url 'blogPosts:delete' id=post.id %}">delete</a>
        </div>
{% endblock content %}